inflation_data = [
 {
   "cat_id": "foodhotdrinks",
   "page": "Groceries",
   "category": "Food and drink",
   "description": "This includes soft drinks and hot drinks but excludes alcoholic beverages.",
   "inf_values": [],
   "inflation_cdid": "L55P",
   "weight_cdid": "L5CZ",
   "average": 89,
   "average_spend": 276.03
 },
 {
   "cat_id": "spiritswinebeer",
   "page": "Groceries",
   "category": "Alcohol",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L56I",
   "weight_cdid": "L5DT",
   "average": 18,
   "average_spend": 40.30
 },
 {
   "cat_id": "tobacco",
   "page": "Groceries",
   "category": "Tobacco products including e-cigarettes",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L56M",
   "weight_cdid": "L5DX",
   "average": 17,
   "average_spend": 15.60
 },
 {
   "cat_id": "personalcare",
   "page": "Groceries",
   "category": "Personal care items",
   "description": "This includes toilet rolls, toothpaste, deodorants etc.",
   "inf_values": [],
   "inflation_cdid": "L58Y",
   "weight_cdid": "L5GB",
   "average": 19,
   "average_spend": 4.33
 },
 {
   "cat_id": "nongrocery",
   "page": "Groceries",
   "category": "Other non-grocery items",
   "description": "This includes items purchased as part of your regular shop, such as cleaning products, and everyday items like tin foil, bin bags or kitchen rolls.",
   "inf_values": [],
   "inflation_cdid": "L57G",
   "weight_cdid": "L5ER",
   "average": 3,
   "average_spend": 11.70
 },
 {
   "cat_id": "ooh",
   "page": "Housing",
   "category": "Homeowner housing costs",
   "description": "For the purposes of this calculator, you can use your monthly mortgage. If you do not pay a mortgage, do not enter a value.",
   "inf_values": [],
   "inflation_cdid": "L5P7",
   "weight_cdid": "L5PA",
   "average": 187,
   "average_spend": 342.33
 },
 {
   "cat_id": "maintenance",
   "page": "Housing",
   "category": "Home maintainance costs",
   "description": "This includes costs for home repairs, decorating, and improvements.",
   "inf_values": [],
   "inflation_cdid": "L56T",
   "weight_cdid": "L5E6",
   "average": 0,
   "average_spend": 79.73
 },
 {
   "cat_id": "rent",
   "page": "Housing",
   "category": "Rent",
   "description": "If you do not rent your home, do not enter a value.",
   "inf_values": [],
   "inflation_cdid": "L56S",
   "weight_cdid": "L5E5",
   "average": 74,
   "average_spend": 227.50
 },
 {
   "cat_id": "counciltax",
   "page": "Housing",
   "category": "Council Tax and rates",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "DHYU",
   "weight_cdid": "DHZC",
   "average": 32,
   "average_spend": 0
 },
 {
   "cat_id": "electricitygasfuels",
   "page": "Housing",
   "category": "Energy bills",
   "description": "This includes gas, electricity and other fuel costs.",
   "inf_values": [],
   "inflation_cdid": "L56Z",
   "weight_cdid": "L5EC",
   "average": 26,
   "average_spend": 106.17
 },
 {
   "cat_id": "water",
   "page": "Housing",
   "category": "Water and sewerage",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L56W",
   "weight_cdid": "L5E9",
   "average": 9,
   "average_spend": 45.07
 },
 {
   "cat_id": "furniture",
   "page": "Housing",
   "category": "Homewares",
   "description": "This includes items such as furniture, household appliances and tools.",
   "inf_values": [],
   "inflation_cdid": "L576",
   "weight_cdid": "L5EH",
   "average": 46,
   "average_spend": 137.37
 },
 {
   "cat_id": "furniture",
   "page": "Housing",
   "category": "Homewares",
   "description": "This includes items such as furniture, household appliances and tools.",
   "inf_values": [],
   "inflation_cdid": "L579",
   "weight_cdid": "L5EK",
   "average": 46,
   "average_spend": 137.37
 },
 {
   "cat_id": "furniture",
   "page": "Housing",
   "category": "Homewares",
   "description": "This includes items such as furniture, household appliances and tools.",
   "inf_values": [],
   "inflation_cdid": "L57A",
   "weight_cdid": "L5EL",
   "average": 46,
   "average_spend": 137.37
 },
 {
   "cat_id": "furniture",
   "page": "Housing",
   "category": "Homewares",
   "description": "This includes items such as furniture, household appliances and tools.",
   "inf_values": [],
   "inflation_cdid": "L57D",
   "weight_cdid": "L5EO",
   "average": 46,
   "average_spend": 137.37
 },
 {
   "cat_id": "furniture",
   "page": "Housing",
   "category": "Homewares",
   "description": "This includes items such as furniture, household appliances and tools.",
   "inf_values": [],
   "inflation_cdid": "L57E",
   "weight_cdid": "L5EP",
   "average": 46,
   "average_spend": 137.37
 },
 {
   "cat_id": "furniture",
   "page": "Housing",
   "category": "Homewares",
   "description": "This includes items such as furniture, household appliances and tools.",
   "inf_values": [],
   "inflation_cdid": "L57H",
   "weight_cdid": "L5ES",
   "average": 46,
   "average_spend": 137.37
 },
 {
   "cat_id": "mobilephone",
   "page": "Communication",
   "category": "Mobile phones",
   "description": "This includes mobile phone charges and any phone purchases.",
   "inf_values": [],
   "inflation_cdid": "J3DK",
   "weight_cdid": "J4LW",
   "average": 7.56,
   "average_spend": 42.90
 },
 {
   "cat_id": "mobilephone",
   "page": "Communication",
   "category": "Mobile phones",
   "description": "This includes mobile phone charges and any phone purchases.",
   "inf_values": [],
   "inflation_cdid": "J3DM",
   "weight_cdid": "J4LZ",
   "average": 7.56,
   "average_spend": 42.90
 },
 {
   "cat_id": "internet",
   "page": "Communication",
   "category": "Other communications costs",
   "description": "This includes internet or landline telephone bills.",
   "inf_values": [],
   "inflation_cdid": "L585",
   "weight_cdid": "L5FG",
   "average": 11.44,
   "average_spend": 39.00
 },
 {
   "cat_id": "internet",
   "page": "Communication",
   "category": "Other communications costs",
   "description": "This includes internet or landline telephone bills.",
   "inf_values": [],
   "inflation_cdid": "J3DJ",
   "weight_cdid": "J4LV",
   "average": 11.44,
   "average_spend": 39.00
 },
 {
   "cat_id": "internet",
   "page": "Communication",
   "category": "Other communications costs",
   "description": "This includes internet or landline telephone bills.",
   "inf_values": [],
   "inflation_cdid": "J3DL",
   "weight_cdid": "J4LY",
   "average": 11.44,
   "average_spend": 39.00
 },
 {
   "cat_id": "internet",
   "page": "Communication",
   "category": "Other communications costs",
   "description": "This includes internet or landline telephone bills.",
   "inf_values": [],
   "inflation_cdid": "J3DN",
   "weight_cdid": "J4M2",
   "average": 11.44,
   "average_spend": 39.00
 },
 {
   "cat_id": "internet",
   "page": "Communication",
   "category": "Other communications costs",
   "description": "This includes internet or landline telephone bills.",
   "inf_values": [],
   "inflation_cdid": "J3DO",
   "weight_cdid": "J4M3",
   "average": 11.44,
   "average_spend": 39.00
 },
 {
   "cat_id": "vehicles",
   "page": "Transport",
   "category": "The purchase of vehicles",
   "description": "This includes cars, motorcycles and pushbikes.",
   "inf_values": [],
   "inflation_cdid": "L57P",
   "weight_cdid": "L5F2",
   "average": 33,
   "average_spend": 113.97
 },
 {
   "cat_id": "petroldiesel",
   "page": "Transport",
   "category": "Petrol or diesel",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L57V",
   "weight_cdid": "L5F8",
   "average": 21,
   "average_spend": 96.63
 },
 {
   "cat_id": "othermotoring",
   "page": "Transport",
   "category": "Other motoring costs",
   "description": "This includes car tax, repairs, parking costs, and car or van hire.",
   "inf_values": [],
   "inflation_cdid": "L57U",
   "weight_cdid": "L5F7",
   "average": 37,
   "average_spend": 49.40
 },
 {
   "cat_id": "othermotoring",
   "page": "Transport",
   "category": "Other motoring costs",
   "description": "This includes car tax, repairs, parking costs, and car or van hire.",
   "inf_values": [],
   "inflation_cdid": "L57W",
   "weight_cdid": "L5F9",
   "average": 37,
   "average_spend": 49.40
 },
 {
   "cat_id": "othermotoring",
   "page": "Transport",
   "category": "Other motoring costs",
   "description": "This includes car tax, repairs, parking costs, and car or van hire.",
   "inf_values": [],
   "inflation_cdid": "L57X",
   "weight_cdid": "L5FA",
   "average": 37,
   "average_spend": 49.40
 },
 {
   "cat_id": "trainfares",
   "page": "Transport",
   "category": "Train fares",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L57Z",
   "weight_cdid": "L5FC",
   "average": 5,
   "average_spend": 19.93
 },
 {
   "cat_id": "busfares",
   "page": "Transport",
   "category": "Bus fares",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L582",
   "weight_cdid": "L5FD",
   "average": 8,
   "average_spend": 6.50
 },
 {
   "cat_id": "electrical",
   "page": "Leisure",
   "category": "Electrical items",
   "description": "This includes TVs, laptops, tablet, cameras, CDs, DVDs and Blu-rays, but excludes mobile phones which are covered in Communications.",
   "inf_values": [],
   "inflation_cdid": "L587",
   "weight_cdid": "L5FI",
   "average": 23,
   "average_spend": 19.50
 },
 {
   "cat_id": "tv",
   "page": "Leisure",
   "category": "TV licence fees and media subscriptions",
   "description": "This includes on-demand TV and music streaming services.",
   "inf_values": [],
   "inflation_cdid": "J3FL",
   "weight_cdid": "J4XB",
   "average": 4.4,
   "average_spend": 20.37
 },
 {
   "cat_id": "tv",
   "page": "Leisure",
   "category": "TV licence fees and media subscriptions",
   "description": "This includes on-demand TV and music streaming services.",
   "inf_values": [],
   "inflation_cdid": "J3FM",
   "weight_cdid": "J4XC",
   "average": 12.6,
   "average_spend": 44.63
 },
 {
   "cat_id": "games",
   "page": "Leisure",
   "category": "Games and toys",
   "description": "This includes games consoles and games.",
   "inf_values": [],
   "inflation_cdid": "L58G",
   "weight_cdid": "L5FR",
   "average": 21,
   "average_spend": 13.87
 },
 {
   "cat_id": "entertainment",
   "page": "Leisure",
   "category": "Entertainment and days out",
   "description": "This includes tickets to attractions, concerts, sporting events, season tickets and gym memberships.",
   "inf_values": [],
   "inflation_cdid": "L58L",
   "weight_cdid": "L5FW",
   "average": 12.6,
   "average_spend": 44.63
 },
 {
   "cat_id": "entertainment",
   "page": "Leisure",
   "category": "Entertainment and days out",
   "description": "This includes tickets to attractions, concerts, sporting events, season tickets and gym memberships.",
   "inf_values": [],
   "inflation_cdid": "J3FJ",
   "weight_cdid": "J4X9",
   "average": 12.6,
   "average_spend": 44.63
 },
 {
   "cat_id": "entertainment",
   "page": "Leisure",
   "category": "Entertainment and days out",
   "description": "This includes tickets to attractions, concerts, sporting events, season tickets and gym memberships.",
   "inf_values": [],
   "inflation_cdid": "J3FK",
   "weight_cdid": "J4XA",
   "average": 12.6,
   "average_spend": 44.63
 },
 {
   "cat_id": "entertainment",
   "page": "Leisure",
   "category": "Entertainment and days out",
   "description": "This includes tickets to attractions, concerts, sporting events, season tickets and gym memberships.",
   "inf_values": [],
   "inflation_cdid": "J3FN",
   "weight_cdid": "J4XD",
   "average": 12.6,
   "average_spend": 44.63
 },
 {
   "cat_id": "pets",
   "page": "Leisure",
   "category": "Pets",
   "description": 'This includes food and vet fees but excludes pet insurance which is included in the "Insurance and financial services" category on the following page.',
   "inf_values": [],
   "inflation_cdid": "L58J",
   "weight_cdid": "L5FU",
   "average": 10,
   "average_spend": 12.13
 },
 {
   "cat_id": "gardening",
   "page": "Leisure",
   "category": "Gardening, plants and flowers",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L58I",
   "weight_cdid": "L5FT",
   "average": 5,
   "average_spend": 7.37
 },
 {
   "cat_id": "eatingout",
   "page": "Leisure",
   "category": "Eating and drinking out",
   "description": "This includes pubs, restaurants, takeaways and canteens.",
   "inf_values": [],
   "inflation_cdid": "L58S",
   "weight_cdid": "L5G5",
   "average": 57,
   "average_spend": 178.97
 },
 {
   "cat_id": "holidays",
   "page": "Leisure",
   "category": "Holidays",
   "description": "This includes travel fares and hotel accomodation, including UK stays.",
   "inf_values": [],
   "inflation_cdid": "L583",
   "weight_cdid": "L5FE",
   "average": 24,
   "average_spend": 237.03

 },
 {
   "cat_id": "holidays",
   "page": "Leisure",
   "category": "Holidays",
   "description": "This includes travel fares and hotel accomodation, including UK stays.",
   "inf_values": [],
   "inflation_cdid": "L584",
   "weight_cdid": "L5FF",
   "average": 24,
   "average_spend": 237.03
 },
 {
   "cat_id": "holidays",
   "page": "Leisure",
   "category": "Holidays",
   "description": "This includes travel fares and hotel accomodation, including UK stays.",
   "inf_values": [],
   "inflation_cdid": "L58R",
   "weight_cdid": "L5G4",
   "average": 24,
   "average_spend": 237.03
 },
 {
   "cat_id": "holidays",
   "page": "Leisure",
   "category": "Holidays",
   "description": "This includes travel fares and hotel accomodation, including UK stays.",
   "inf_values": [],
   "inflation_cdid": "L58V",
   "weight_cdid": "L5G8",
   "average": 24,
   "average_spend": 237.03
 },
 {
   "cat_id": "otherleisure",
   "page": "Leisure",
   "category": "Other leisure items",
   "description": "This includes books, newspapers, personal effects such as jewellery or watches, sports equipment, and major durable items like musical instruments or caravans.",
   "inf_values": [],
   "inflation_cdid": "L58D",
   "weight_cdid": "L5FO",
   "average": 38,
   "average_spend": 52.87
 },
 {
   "cat_id": "otherleisure",
   "page": "Leisure",
   "category": "Other leisure items",
   "description": "This includes books, newspapers, personal effects such as jewellery or watches, sports equipment, and major durable items like musical instruments or caravans.",
   "inf_values": [],
   "inflation_cdid": "L58H",
   "weight_cdid": "L5FS",
   "average": 38,
   "average_spend": 52.87
 },
 {
   "cat_id": "otherleisure",
   "page": "Leisure",
   "category": "Other leisure items",
   "description": "This includes books, newspapers, personal effects such as jewellery or watches, sports equipment, and major durable items like musical instruments or caravans.",
   "inf_values": [],
   "inflation_cdid": "L58N",
   "weight_cdid": "L5FY",
   "average": 38,
   "average_spend": 52.87
 },
 {
   "cat_id": "otherleisure",
   "page": "Leisure",
   "category": "Other leisure items",
   "description": "This includes books, newspapers, personal effects such as jewellery or watches, sports equipment, and major durable items like musical instruments or caravans.",
   "inf_values": [],
   "inflation_cdid": "L58Z",
   "weight_cdid": "L5GC",
   "average": 38,
   "average_spend": 52.87
 },
 {
   "cat_id": "health",
   "page": "Other",
   "category": "Healthcare",
   "description": 'This includes prescription charges, private healthcare, and dental and physiotherapy treatments but not health or dental insurance which should be included in the "Insurance and financial services" category.',
   "inf_values": [],
   "inflation_cdid": "L55U",
   "weight_cdid": "L5D6",
   "average": 24,
   "average_spend": 54.60
 },
 {
   "cat_id": "health",
   "page": "Other",
   "category": "Healthcare",
   "description": 'This includes prescription charges, private healthcare, and dental and physiotherapy treatments but not health or dental insurance which should be included in the "Insurance and financial services" category.',
   "inf_values": [],
   "inflation_cdid": "L58X",
   "weight_cdid": "L5GA",
   "average": 24,
   "average_spend": 54.60
 },
 {
   "cat_id": "education",
   "page": "Other",
   "category": "Education costs",
   "description": "This includes university tuition fees, private school fees, and leisure classes, but not  accommodation costs.",
   "inf_values": [],
   "inflation_cdid": "L55Y",
   "weight_cdid": "L5DA",
   "average": 30,
   "average_spend": 19.50
 },
 {
   "cat_id": "residentialcare",
   "page": "Other",
   "category": "Residential care",
   "description": "This includes retirement home fees for elderly patients.",
   "inf_values": [],
   "inflation_cdid": "J3J6",
   "weight_cdid": "J4YC",
   "average": 19,
   "average_spend": 86.63
 },
 {
   "cat_id": "residentialcare",
   "page": "Other",
   "category": "Residential care",
   "description": "This includes retirement home fees for elderly patients.",
   "inf_values": [],
   "inflation_cdid": "J3JP",
   "weight_cdid": "J4YD",
   "average": 19,
   "average_spend": 86.63
 },
 {
   "cat_id": "childcare",
   "page": "Other",
   "category": "Childcare costs",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "J3GL",
   "weight_cdid": "J4YB",
   "average": 19,
   "average_spend": 86.63
 },
 {
   "cat_id": "clothes",
   "page": "Other",
   "category": "Clothes and footwear",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L55R",
   "weight_cdid": "L5D3",
   "average": 59,
   "average_spend": 101.40
 },
 {
   "cat_id": "insurance",
   "page": "Other",
   "category": "Insurance and financial services",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L595",
   "weight_cdid": "L5GG",
   "average": 30,
   "average_spend": 24.30
 },
 {
   "cat_id": "insurance",
   "page": "Other",
   "category": "Insurance and financial services",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L599",
   "weight_cdid": "L5GK",
   "average": 30,
   "average_spend": 24.30
 },
 {
   "cat_id": "insurance",
   "page": "Other",
   "category": "Insurance and financial services",
   "description": "Add description here...",
   "inf_values": [],
   "inflation_cdid": "L59B",
   "weight_cdid": "L5GM",
   "average": 30,
   "average_spend": 24.30
 },
 {
   "cat_id": "other",
   "page": "Other",
   "category": "Other expenditure",
   "description": "Any other expenditure not already accounted for.",
   "inf_values": [],
   "inflation_cdid": "L55O",
   "weight_cdid": "L5CY",
   "average": 0,
   "average_spend": 0
 }
]
